# Generated by Django 4.0.5 on 2022-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_task_id_alter_category_name_alter_task_end_date_and_more'),
    ]

    operations = [
        
    ]
